name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
      - name: Install dependencies
        run: npm install --production
      - name: Build the app
        run: npm run build
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          author: Johann Pardanaud <johann@pardanaud.com>
          build_dir: build
          target_branch: gh-pages
          fqdn: ffmpegen.nesk.dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
